### ISSUE TITLE
Overwrite error when running with MPI

### ISSUE THREAD

**Issue by andyyPark** [mr-superonion/FPFS#12]
https://github.com/mr-superonion/FPFS/blob/00ad0a00d72c6f66e73eafc253d10af09aac354d/bin/fpfs_process_sim.py#L135

When first running the simulatoin with MPI, each task sees there is no covariance file and tries to write one.

**Comment by mr-superonion** [comment]
Forcing it only to run for rank==0: https://github.com/mr-superonion/FPFS/commit/d9553d624ccf96f4887b1722be2b035f6c3817e8

**Comment by andyyPark** [comment]
I am still getting the same issue

**Comment by andyyPark** [comment]
Never mind!

**Comment by andyyPark** [comment]
Fixed by f9ac45b6cdbf6790aa527e3985e39c42222debcd
