### ISSUE TITLE
Different number of columns for 4th order fpfs catalog

### ISSUE THREAD

**Issue by andyyPark** [mr-superonion/FPFS#14]
Fpfs needs to change the number of columns / columns names / columns indexes for 4th order. `ncol` should be 32 for 4th order.

https://github.com/mr-superonion/FPFS/blob/00ad0a00d72c6f66e73eafc253d10af09aac354d/fpfs/catalog.py#L771

**Comment by mr-superonion** [comment]
Solved in https://github.com/mr-superonion/FPFS/pull/15
