### ISSUE TITLE
Question about `sigma_arcsec` in `fpfs.image.measure_source()`

### ISSUE THREAD

**Issue by Lukeli0425** [mr-superonion/FPFS#5]
Hi there!

I'm using your fpfs to estimate shape of galaxies in my project. I noticed that you updated your code, and I wonder what the `sigma_arcsec` in `fpfs.image.measure_source()` is and how to choose a proper value? I did not relevant info found in the documentations.

Thanks for paying attention!

**Comment by mr-superonion** [comment]
Hello, `sigma_arcsec` is the scale of Gaussian smoothing kernel in units of `arcsec`. 
It depends on your PSF size, the smoothing kernel need to be larger than the typical scale of PSF to prevent the PSF deconvolution process boost noise at small scales (large |k|).

For HSC-like data, with PSF FWHM = 0.6 arcsec,  I have tested the code performance `sigma_arcsec= 0.45` (equivalent to FWHM=1.1 arcsec) and `sigma_arcsec=0.6` (equivalent to FWHM=1.4 arcsec) . You can find the performance of the shear estimator from figures 15 and 16 in this paper: https://arxiv.org/pdf/2208.10522.pdf

This unit test might be useful as an example on how to use the code:
https://github.com/mr-superonion/FPFS/blob/master/fpfs/tests/test_basic2_basesim_noiseless_shearest.py

**Comment by Lukeli0425** [comment]
Thank you!
